[book]
authors = ["Giuseppe Barillari"]
language = "en"
multilingual = false
src = "src"
title = "ManyCore Visualiser User Manual"

[preprocessor.download]
command = "python3 download_preprocessor.py"

[output.html]
additional-css = ["src/custom.css"]