[book]
authors = ["Giuseppe Barillari"]
language = "en"
multilingual = false
src = "src"
title = "ManyCore Visualiser User Manual"

[preprocessor.download]
command = "python3 download_preprocessor.py"

[output.html]
additional-js = ["js/video.min.js"]
additional-css = ["css/manycore.css", "css/emoji.css", "css/video-js.css"]
site-url = "/manual/"